### ISSUE TITLE
Feedback for “Price Lists Records”

### ISSUE THREAD

**Issue by paulopompeu** [bigcommerce/docs#204]
Which value should I send to remove the price overriding the catalog price?

I'm trying to remove the new price from an item so BigCommerce can use the catalog price. The upsert request doesn't accept: null, "", {}, etc... when I send 0.00, it becomes the new price instead.

```
curl --request PUT \
  --url 'https://api.bigcommerce.com/stores/store/v3/pricelists/1/records' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --header 'X-Auth-Token: token' \
  --data '[{"sku":"999P7068","currency":"usd","price": 0 }]'
```

Thank you

**Comment by slsriehl** [comment]
Hi @paulopompeu -- good question! I've passed this question along to our price lists team and will keep you posted.

Thanks for opening this issue and building with BC.

**Comment by bc-tgomez** [comment]
Hey @paulopompeu. Thanks for the question and for your patience while we gathered the answer. 

In this case, the most helpful solution would be to delete the price record. Deleting the price record then removes the new price and defaults it back to your catalog; because a price record no longer exists.

I hope to have answered your question. If you have more questions, please feel free to follow up in this thread or create a new issue.
