### ISSUE TITLE
/v3/catalog/products?categories:in=123,456

### ISSUE THREAD

**Issue by propsmagic** [bigcommerce/docs#217]
/v3/catalog/products?categories:in=123,456 this API endpoints doesn't work but /v3/catalog/products?categories:not_in=123,456 this is working

**Comment by bc-andreadao** [comment]
@propsmagic The endpoint query parameter worked when I tested it, but to be sure, we'll get some support eyes on this.

**Comment by robincoferbc** [comment]
@propsmagic as @bc-andreadao mentioned this works when tested, but to fully troubleshoot, we would need to study the individual details of a specific store where the issue is occurring. Please [submit a support case](https://support.bigcommerce.com/s/article/Creating-Viewing-Support-Cases) for your store, and our support team will be happy to dig into the details.

**Comment by slsriehl** [comment]
Referred to support; closing issue. Thanks for building with BC and opening this issue, @propsmagic!
