### ISSUE TITLE
Feedback for “Single-Click App Callback Handlers”

### ISSUE THREAD

**Issue by zzj0124** [bigcommerce/docs#483]
There is no callback request '/uninstall' received, when I click the Uninstall button on my app's card in the store control panel.
Please help me!
![企业微信截图_17248978085250](https://github.com/user-attachments/assets/796934e6-1983-4490-af60-b2f2070d2ad8)

**Comment by bc-traciporter** [comment]
Hello @zzj0124 Thank you for your feedback. Since you are asking about a control panel issue, we suggest that you contact support.
You can use the following link, or if you are a registered partner, you can submit a case via the partner portal.
https://support.bigcommerce.com/s/contact?language=en_US
