### ISSUE TITLE
Feedback for “Manage Webhooks Single”

### ISSUE THREAD

**Issue by cjbarth** [bigcommerce/docs#505]
Your documentation doesn't say that any fields are required. However, I when I call "Update a Webhook" and only pass in `{"events_history_enabled": true}`, I get the following error:

```json
{
    "status": 422,
    "title": "The following fields are invalid: data",
    "type": "https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes",
    "errors": {
        "data": "Update webhook request should not be empty"
    }
}
```

If I add `scope` or `destination` or `is_active`, then I don't get an error. This isn't clear from your documentation, and I can't figure out why it would matter.

**Comment by bc-traciporter** [comment]
Hello @cjbarth Sorry for the delayed response. We are looking into your tickets. For now, I have started a Pull Request to address the needed changes for this issue. I will remove `events_history-enabled` since it is not a supported field. 
Also you need at least one field to perform the Update a Webhook request. Once I receive all the specifications, I will update the docs. Thank you for your patience.

**Comment by cjbarth** [comment]
Ok, it makes sense that if `events_history_enabled` is not a supported field, I would need some other field that was supported. I might also add that when I get all webhooks, I do see the property `events_history_enabled`, with a value of `falase` always, so your API still returns that value, so that API might need to be adjusted too.

**Comment by bc-traciporter** [comment]
Closing ticket, the updates have been merged in this PR
https://github.com/bigcommerce/docs/pull/513
