### ISSUE TITLE
Custom Payment processing

### ISSUE THREAD

**Issue by usmanhttp** [bigcommerce/docs#639]
Hi ,
I want to integrate my big commerce with one of my customer payment gateway.
for example: I have another payment solution system that supports multiple payment gateways. Is that possible to achieve this in big commerce?
if yes , then please help me do this
-Thanks

**Comment by bc-traciporter** [comment]
Hello @usmanhttp 
I understand that you would like to integrate a custom payment gateway into your BigCommerce store. This is something that will take quite a bit of custom work and development to be able to do. Due to this our support staff is not able to advise on how to implement this due to custom coding being outside of our scope of support.

Here are some resources that may be helpful if you still do want to integrate a payment gateway that we do not natively support:

- First is a [community post](https://support.bigcommerce.com/s/question/0D54O00006AnpShSAJ/i-want-to-integrate-custom-payment-gateway-with-bigcommerce?language=en_US) that describes the typical process taken to integrate a custom payment solution.

- Next is the [overview of our Checkout SDK](https://developer.bigcommerce.com/stencil-docs/customizing-checkout/checkout-sdk-quickstart) that can be used to customize a store's checkout .

- And last is the [source code for our Checkout SDK](https://github.com/bigcommerce/checkout-sdk-js). This may help if the integration that you build needs a custom checkout experience. 

Typically custom payment gateways are not recommended, but if they are needed a Solutions Architect is the service you would need on our side.
